apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
  labels:
    app: grafana
data:
  grafana.ini: |
    [server]
    http_port = 3000
    domain = localhost
    
    [database]
    type = sqlite3
    path = /var/lib/grafana/grafana.db
    
    [security]
    admin_user = admin
    admin_password = admin
    
    [users]
    allow_sign_up = false
    
    [auth.anonymous]
    enabled = false
    
    [log]
    mode = console
    level = info
    
    [metrics]
    enabled = true
    
    [alerting]
    enabled = true
    
    [unified_alerting]
    enabled = true
    
    [feature_toggles]
    enable = unifiedAlerting
    
    [panels]
    enable_alpha = false
    
    [plugins]
    allow_loading_unsigned_plugins = false
