name: production
url: https://prod.example.com
protection_rules:
  - required_reviewers:
      users: [cto, devops-director, security-lead]
      teams: [senior-devops, security-team]
  - wait_timer:
      minutes: 10
  - required_status_checks:
      strict: true
      contexts:
        - "Security Scan"
        - "Quality Gates"
        - "Infrastructure Validation"
        - "Container Build"
        - "Deploy Development"
        - "Deploy Staging"
  - deployment_branch_policy:
      protected_branches: true
      custom_branch_policies: false
  - required_conversation_resolution: true 